language: java
install: ./gradlew -Pci assemble dokka --no-daemon
script: ./gradlew -Pci check
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: docs/plumber
  on:
    branch: master
