/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package me.bristermitten.plumber;

import co.aikar.commands.annotation.CommandAlias;
import me.bristermitten.plumber.aspect.AspectLoader;
import me.bristermitten.plumber.command.CommandAspect;
import org.bukkit.plugin.PluginDescriptionFile;
import org.bukkit.plugin.java.JavaPlugin;
import org.bukkit.plugin.java.JavaPluginLoader;
import org.jetbrains.annotations.NotNull;
import org.reflections.Configuration;
import org.reflections.Reflections;
import org.reflections.util.ConfigurationBuilder;

import java.io.File;
import java.net.URISyntaxException;

/**
 * Main class of the project
 * Plumber equivalent of SpringApplication
 */
public class PlumberPlugin extends JavaPlugin {
    public PlumberPlugin() {
    }

    public PlumberPlugin(@NotNull JavaPluginLoader loader, @NotNull PluginDescriptionFile description,
                         @NotNull File dataFolder, File file) {
        super(loader, description, dataFolder, file);
    }

    protected void loadPlugin() {
        String ourPackage = getClass().getPackage().getName();
        Configuration config = new ConfigurationBuilder().forPackages(ourPackage);
        Reflections reflections = new Reflections(config);

        new AspectLoader(this, reflections)
                .addThirdPartyAspectAnnotation(CommandAlias.class, CommandAspect.class).loadAll();
    }
}
